// Generated by scripts/record-candidate-eligibility-demo.ts from a real Responses API call.
// Synthetic DEMO_MODE data only. Re-record when any pin or prompt hash changes.
export const CANDIDATE_ELIGIBILITY_RECORDED_LIVE = {
  schema_version: "candidate-eligibility-recorded-live@1",
  operation: "deriveCandidateEligibilityMatches",
  prompt_version: "onlyboth.derive-candidate-eligibility-matches@1.0.0",
  prompt_hash: "sha256:a47d3c03fc59dab7b61c109ac9f0c88e028cd0670e6371b3a049d9bde10ad7b7",
  requested_model: "gpt-5.6-sol",
  resolved_model: "gpt-5.6-sol",
  provider_response_id: "resp_0966dcbfe09cd8dc016a5fc21ad494819a880e6699843d6f90",
  recorded_at: "2026-07-21T19:01:56.897Z",
  input_hash: "sha256:dc0a336cee1f75c1b9af240e86636a42dc434428ef021dd9000b57adec4d5a72",
  output_hash: "sha256:1e83952c9c1b3a2a94dcd413d357cb125207c6a306e320c8ed87b9d06adfdc04",
  pins: {
    candidate_ref: "candidate-42",
    passport_snapshot_ref: "passport-snapshot:candidate-42:preloaded-v1",
    passport_snapshot_hash:
      "sha256:9edbe9e39e21e69b2046d1b546d5036215380b61a0ca32ccf55376764d41b61e",
    opportunity_ref: "functional-demo-job:opportunity:1",
    opportunity_version: 1,
    contract_hash: "sha256:33dfa899c313ab215d56ff226e0c639c7af861b7848b40bc144c73264c130c00",
  },
  output: {
    schema_version: "candidate-eligibility-match-output@1",
    matches: [
      {
        opportunity_ref: "functional-demo-job:opportunity:1",
        state: "POSITIVE_EVIDENCE",
        connections: [
          {
            tag_ref: "eligibility-tag:education:computer-science@1",
            evidence_refs: ["education:candidate-42:highest-v1"],
            connection_type: "EDUCATION",
            bounded_reason:
              "The education source states a computer science field of study, directly corresponding to the Computer Science education tag.",
            still_unknown: [
              "The source does not establish the curriculum content or depth of study.",
            ],
          },
          {
            tag_ref: "eligibility-tag:work:backend-engineering@1",
            evidence_refs: ["evidence:employment-verification"],
            connection_type: "WORK_EXPERIENCE",
            bounded_reason:
              "The employment source states a backend engineering function, directly corresponding to the Backend Engineering work-domain tag.",
            still_unknown: [
              "The record does not describe responsibilities, projects, or scope within that function.",
            ],
          },
          {
            tag_ref: "eligibility-tag:work:backend-engineering@1",
            evidence_refs: ["evidence:github-payment-retry"],
            connection_type: "OTHER_EVIDENCE",
            bounded_reason:
              "The repository source describes implementation of idempotency keys, retry state transitions, and integration tests, which directly concern backend engineering work.",
            still_unknown: [
              "The snapshot does not establish the breadth, duration, or production use of the described work.",
            ],
          },
          {
            tag_ref: "eligibility-tag:work:backend-engineering@1",
            evidence_refs: ["evidence:incident-work-sample"],
            connection_type: "WORK_SAMPLE",
            bounded_reason:
              "The work sample describes Redis failover analysis and recovery checks, directly connecting it to backend engineering systems work.",
            still_unknown: [
              "The sample does not establish whether the proposed recovery approach was implemented or used in a live system.",
            ],
          },
        ],
      },
    ],
  },
} as const;
